### ISSUE TITLE
Use new pixi middleware in v3.0.2

### ISSUE THREAD

**Issue by englercj** [beeglebug/pixi-tiled#1]
Going out with v3.0.2 will be this code:

https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/loaders/loader.js#L42-L55

You can register a middleware to always be on the loader that people create with `new PIXI.loaders.Loader()`.

So basically in your plugin do:

``` js
PIXI.loaders.Loader.addPixiMiddleware(myMiddlewareFn);
PIXI.loader.use(myMiddlewareFn()); // don't forget the premade one!
```

And everyone gets the benefits of your middleware transparently.

**Comment by beeglebug** [comment]
Great stuff. I'll update it accordingly, thanks for the heads up.

**Comment by englercj** [comment]
Np, I just wrote it today so many be a week or so before it is released.

**Comment by beeglebug** [comment]
Cool, I'll keep an eye out.

**Comment by englercj** [comment]
Heads up as well: No longer do `require('pixi.js')`, just use PIXI as an implicit global. You can see these issues for more details:

https://github.com/GoodBoyDigital/pixi.js/issues/1713
https://github.com/pixijs/pixi-spine/issues/20
