### ISSUE TITLE
json maps missing image, dimensions, and maybe more

### ISSUE THREAD

**Issue by timetocode** [beeglebug/pixi-tiled#19]
I'm not sure if there has been a change in Tiled formats since this library was made, but I can't seem to get my json maps to load. Here's one of them exported (with the layer data removed to keep it human-readable).

{ "height":13,
 "layers":[], // SKIPPED
 "nextobjectid":1,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.0.2",
 "tileheight":16,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/art\/mountain-map.tsx"
        }],
 "tilewidth":16,
 "type":"map",
 "version":1,
 "width":17
}

See where it says"source":"..\/art\/mountain-map.tsx"  ? That's all it puts there.  How do I make this work? From reading the test cases it seems like that area would need at least an image, and possibly more data. I'm not sure what to type in there to hack it into working by hand -- or how to get an export in the correct form to begin with.

**Comment by beeglebug** [comment]
Hi, I haven't updated this library in a while, I think recently Tiled switched to separate files for each tilemap inside a map, which this won't handle. I think there might be a way to tell Tiled not to do that in the map settings, which might get it working again, but no guarantees!

**Comment by timetocode** [comment]
That was spot on about the separate files.

So the way to get this in the correct format now is to create a **New Tileset** and then select **Embed in map**.  This will populate those necessary fields.  As far as I can tell this can't be done retroactively QQ, it has to be done at the start or a map won't work. 

I was able to get a small map loaded and displayed in PIXI v4.3.4 and Tiled v1.0.2. 
Thanks for your help!
