### ISSUE TITLE
Add Pixi.js as peerDep

### ISSUE THREAD

**Issue by englercj** [beeglebug/pixi-tiled#4]
Right now it is unclear what versions of this lib depend on what versions of pixi.

You should add pixi as a `peerDependency` of this library so people can know (and npm can warn).

See https://github.com/pixijs/pixi-spine/blob/master/package.json#L26-L28 for how to add them. `3.0.2` is required if you have made the implicit global changes.

**Comment by beeglebug** [comment]
Funnily enough I already thought of this (see #2) then closed it because I
wasn't 100% sure how peerDependancies worked. I'll add it back in.

**Comment by englercj** [comment]
It just makes npm warn if people don't put pixi as a dep when they use this module in a browserify senario. It also lets users read the package file to know what pixi version they need when using a version of your module.
